/**
 * Ambient type for the **vendored** Symphonia-in-wasm glue (`./vorbis-core.js`), produced by
 * `wasm-pack build --target web` (renamed from `vorbis_wasm.js`) — see `BUILD.md`. The `.wasm` + this
 * glue are committed build artifacts; this declaration types the driver's string-literal
 * `import('./vorbis-core.js')` so it typechecks + code-splits. The shape matches the generated
 * `vorbis_wasm.d.ts` exactly (the `VorbisWasm` class + the `--target web` default init).
 */
export {}; // make this a module so the relative `declare module` below is an augmentation

declare module './vorbis-core.js' {
  /** The live Vorbis decoder the wasm exposes (generated by wasm-bindgen from the Rust `VorbisWasm`). */
  export class VorbisWasm {
    /** Build from the Vorbis codec `extra_data` (Xiph-laced or concatenated ident‖setup) + geometry. */
    constructor(extra_data: Uint8Array, channels: number, sample_rate: number);
    /** Channel count (container-declared, reconciled with the decoded spec). */
    readonly channels: number;
    /** Sample rate in Hz (container-declared, reconciled with the decoded spec). */
    readonly sampleRate: number;
    /** Decode one Vorbis audio packet → interleaved f32 (`frames × channels`); may be empty. */
    decode(data: Uint8Array): Float32Array;
    /** Reset overlap-add state at a discontinuity. */
    reset(): void;
    /** Release the native decoder. */
    free(): void;
  }

  /**
   * The inputs wasm-bindgen's `--target web` init accepts (mirrors the generated `InitInput`): a URL/
   * Response to fetch, raw module bytes, or a precompiled `WebAssembly.Module` (the last lets it run in
   * Node, where there is no fetch).
   */
  type InitInput = RequestInfo | URL | Response | BufferSource | WebAssembly.Module;

  /**
   * wasm-bindgen (`--target web`) init: instantiates the module, fetching the sibling `*_bg.wasm` when
   * given a URL. The driver passes `{ module_or_path: new URL('./vorbis_wasm_bg.wasm', import.meta.url) }`
   * so the bundler emits the wasm same-origin (no CDN, no COOP/COEP).
   */
  export default function init(
    moduleOrPath?: { module_or_path: InitInput } | InitInput,
  ): Promise<unknown>;
}
