/**
 * Ambient type for the **vendored** Symphonia-in-wasm glue (`./aac-core.js`), produced by `wasm-pack
 * build --target web` (renamed from `aac_wasm.js`) — see `BUILD.md`. The `.wasm` + this glue are
 * committed build artifacts; this declaration types the driver's string-literal `import('./aac-core.js')`
 * so it typechecks + code-splits. The shape matches the generated `aac_wasm.d.ts` exactly (the `AacWasm`
 * class + the `--target web` default init).
 */
export {}; // make this a module so the relative `declare module` below is an augmentation

declare module './aac-core.js' {
  /** The live AAC-LC decoder the wasm exposes (generated by wasm-bindgen from the Rust `AacWasm`). */
  export class AacWasm {
    /** Build from the AAC `extra_data` (AudioSpecificConfig; may be empty for ADTS) + geometry. */
    constructor(extra_data: Uint8Array, channels: number, sample_rate: number);
    /** Channel count (container-declared, reconciled with the decoded spec). */
    readonly channels: number;
    /** Sample rate in Hz (container-declared, reconciled with the decoded spec). */
    readonly sampleRate: number;
    /** Decode one raw AAC packet (no ADTS header) → interleaved f32 (`frames × channels`). */
    decode(data: Uint8Array): Float32Array;
    /** Reset decoder state at a discontinuity. */
    reset(): void;
    /** Release the native decoder. */
    free(): void;
  }

  /** The inputs wasm-bindgen's `--target web` init accepts (mirrors the generated `InitInput`). */
  type InitInput = RequestInfo | URL | Response | BufferSource | WebAssembly.Module;

  /**
   * wasm-bindgen (`--target web`) init: instantiates the module, fetching the sibling `*_bg.wasm` when
   * given a URL. The driver passes `{ module_or_path: new URL('./aac_wasm_bg.wasm', import.meta.url) }`
   * so the bundler emits the wasm same-origin (no CDN, no COOP/COEP).
   */
  export default function init(
    moduleOrPath?: { module_or_path: InitInput } | InitInput,
  ): Promise<unknown>;
}
